Improve pre-commit hook a bit more

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,31 +1,29 @@
 printf "Running pre-commit hooks\n\n"
 
-
-
 STAGED=$(git diff --name-only --staged | grep -i ".elm$")
 
 if [[ -n "$STAGED" ]]; then
+
     printf "  1. Running elm-format... "
+
     if elm-format "$STAGED" --yes ; then
         printf "Success!\n\n"
     else 
         printf "Failed!\n\n"
         exit 1
     fi
+
+    printf "  2. Generating docs.json... "
+
+    if elm make --docs=docs.json > /dev/null 2>&1; then
+        git add docs.json
+        printf "Success!\n\n"
+    else 
+        printf "Failed!\n\n"
+        exit 1
+    fi
+
 fi
-
-printf "  2. Generating docs.json... "
-
-if elm make --docs=docs.json > /dev/null 2>&1; then
-    printf "Success!\n\n"
-else 
-    printf "Failed!\n\n"
-    exit 1
-fi
-
-printf "  3. Staging changed files\n\n"
-
-git add docs.json
 
 printf "Pre-commit hooks complete\n\n"
 
